name: Slim CD Pipeline

on:
  push:
    branches:
      - master
      
jobs:
  build:
    environment: Default
    strategy:
      matrix:
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      Configuration: Release
      Solution_Path: Slim.slnx
      Test_Project_Path: Slim.Tests\Slim.Tests.csproj
      Source_Project_Path: Slim\Slim.csproj
      Integration_Project_Path: Slim.Integration\Slim.Integration.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Path

    - name: Build Slim project
      run: dotnet build Slim -c $env:Configuration --no-restore

    - name: Build Slim.Integration project
      run: dotnet build $env:Integration_Project_Path -c $env:Configuration --no-restore

    - name: Package Slim
      run: dotnet pack -c Release -o . $env:Source_Project_Path --no-build

    - name: Package Slim.Integration
      run: dotnet pack -c Release -o . $env:Integration_Project_Path --no-build

    - name: Publish
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate