name: Slim CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      Solution_Path: Slim.slnx
      Test_Project_Path: Slim.Tests\Slim.Tests.csproj
      Integration_Test_Project_Path: Slim.Integration.Tests\Slim.Integration.Tests.csproj
      Source_Project_Path: Slim\Slim.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Path

    - name: Build solution
      run: dotnet build $env:Solution_Path --no-restore --configuration Release

    - name: Execute Slim Unit Tests
      run: dotnet test $env:Test_Project_Path --no-build --configuration Release --verbosity normal
    
    - name: Execute Slim.Integration Unit Tests
      run: dotnet test $env:Integration_Test_Project_Path --no-build --configuration Release --verbosity normal